kind: pipeline
name: default
steps:
  - name: test
    image: golang
    commands:
      - GO111MODULE=off go get github.com/mattn/goveralls
      - goveralls -service drone.io
  - name: lint
    image: golang
    commands:
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
      - golangci-lint run .
